"""last migrate

Revision ID: 7450f625a66f
Revises: b9eb9a872e5d
Create Date: 2024-06-04 19:46:22.670937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7450f625a66f'
down_revision = 'b9eb9a872e5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_column('day_of_week')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_of_week', sa.VARCHAR(length=255), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
