"""Initial migration.

Revision ID: b7983e23ab79
Revises: 
Create Date: 2024-04-08 22:38:03.801248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7983e23ab79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id_car', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('specification', sa.Text(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id_car')
    )
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'member', name='user_role_enum'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('username')
    )
    op.create_table('orders',
    sa.Column('id_order', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('number_participants', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('status_payment', sa.Boolean(), nullable=False),
    sa.Column('order_status', sa.Enum('pending', 'processing', 'completed', name='order_status_enum'), nullable=False),
    sa.Column('payment_gateway', sa.Enum('midtrans', name='payment_gateway_enum'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_order')
    )
    op.create_table('schedules',
    sa.Column('id_schedule', sa.Integer(), nullable=False),
    sa.Column('id_car', sa.Integer(), nullable=True),
    sa.Column('from_location', sa.String(length=255), nullable=False),
    sa.Column('to_location', sa.String(length=255), nullable=False),
    sa.Column('departure_time', sa.Time(), nullable=False),
    sa.Column('arrival_time', sa.Time(), nullable=False),
    sa.Column('day_of_week', sa.String(length=255), nullable=False),
    sa.Column('date_trip', sa.Date(), nullable=False),
    sa.Column('available_seats', sa.Integer(), nullable=False),
    sa.Column('status_still_available', sa.Boolean(), nullable=False),
    sa.Column('rental_price', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_car'], ['cars.id_car'], ),
    sa.PrimaryKeyConstraint('id_schedule')
    )
    op.create_table('order_schedules',
    sa.Column('id_order', sa.Integer(), nullable=False),
    sa.Column('id_schedule', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_order'], ['orders.id_order'], ),
    sa.ForeignKeyConstraint(['id_schedule'], ['schedules.id_schedule'], ),
    sa.PrimaryKeyConstraint('id_order', 'id_schedule')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_schedules')
    op.drop_table('schedules')
    op.drop_table('orders')
    op.drop_table('users')
    op.drop_table('cars')
    # ### end Alembic commands ###
